"use client";
import {useEffect,useState} from "react";import {useSearchParams,useParams} from "next/navigation";
export default function BookPage(){const {businessSlug}=useParams<{businessSlug:string}>();const q=useSearchParams();const [data,setData]=useState<any>(null),[serviceId,setServiceId]=useState(q.get("service")||""),[date,setDate]=useState(""),[slots,setSlots]=useState<any[]>([]),[slot,setSlot]=useState<any>(null),[form,setForm]=useState({name:"",phone:"",email:"",notes:""}),[busy,setBusy]=useState(false),[done,setDone]=useState<any>(null),[error,setError]=useState("");
useEffect(()=>{fetch(`/api/public/business?slug=${encodeURIComponent(businessSlug)}`).then(r=>r.json()).then(setData)},[businessSlug]);
useEffect(()=>{if(!serviceId||!date)return;setSlot(null);fetch(`/api/public/availability?slug=${encodeURIComponent(businessSlug)}&serviceId=${serviceId}&date=${date}`).then(r=>r.json()).then(x=>setSlots(x.slots||[]))},[businessSlug,serviceId,date]);
if(done)return <main className="auth"><div className="auth-card card"><div className="eyebrow">Booking confirmed</div><h1>You’re booked.</h1><p className="muted">Your booking code is <strong>{done.code}</strong>.</p><p>{done.service} · {new Date(done.startAt).toLocaleString()}</p>{data?.whatsappNumber&&<a className="btn btn-secondary" href={`https://wa.me/${data.whatsappNumber.replace(/\D/g,"")}?text=${encodeURIComponent(`Habari ${data.name}, nimekamilisha booking ${done.code}.`)}`}>Chat on WhatsApp</a>}<a className="btn btn-primary" href={`/${businessSlug}`}>Back to business</a></div></main>;
if(!data)return <main className="container section"><div className="card">Loading booking page…</div></main>;
async function submit(e:any){e.preventDefault();if(!slot)return setError("Choose an available time.");setBusy(true);setError("");const r=await fetch("/api/public/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug:businessSlug,serviceId,staffId:slot.staffId,startAt:`${date}T${slot.time}:00`,...form})});const x=await r.json();setBusy(false);if(!r.ok)return setError(x.error||"Could not create booking.");setDone(x.booking)}
return <main className="auth"><form className="auth-card card" onSubmit={submit}><div className="eyebrow">Book with BrellBook</div><h1>{data.name}</h1><p className="muted">No customer account required.</p><div className="field"><label>1. Service</label><select required value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">Choose service</option>{data.services.map((s:any)=><option key={s.id} value={s.id}>{s.name} · TSh {Number(s.price).toLocaleString()} · {s.durationMin} min</option>)}</select></div><div className="field"><label>2. Date</label><input required type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>3. Available time</label><div className="slot-grid">{slots.length?slots.map((x:any)=><button type="button" key={`${x.time}-${x.staffId}`} className={slot?.time===x.time?"slot selected":"slot"} onClick={()=>setSlot(x)}>{x.time}</button>):<span className="muted">Choose a service and date.</span>}</div></div><div className="field"><label>Your name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Phone / WhatsApp</label><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Email (optional)</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Notes (optional)</label><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>{error&&<p className="error">{error}</p>}<button disabled={busy} className="btn btn-primary" style={{width:"100%"}}>{busy?"Confirming…":"Confirm booking"}</button></form></main>}
