"use client";
import { useState } from "react";
import { Check, ChevronDown, Copy, Menu, X } from "lucide-react";
export function Button({children,className="",variant="primary",...p}:{children:React.ReactNode;className?:string;variant?:'primary'|'secondary'}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`btn ${variant==='secondary'?'btn-secondary':'btn-primary'} ${className}`} {...p}>{children}</button>}
export function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`card ${className}`}>{children}</div>}
export function Badge({children,tone="purple"}:{children:React.ReactNode;tone?:string}){const map:any={purple:'bg-purple-50 text-purple-700',green:'bg-emerald-50 text-emerald-700',yellow:'bg-amber-50 text-amber-700',red:'bg-red-50 text-red-700',slate:'bg-slate-100 text-slate-600'};return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${map[tone]||map.purple}`}>{children}</span>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:React.ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-[#0b0b20]/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-bold">{title}</h3><button onClick={onClose}><X size={20}/></button></div>{children}</div></div>}
export function CopyButton({value}:{value:string}){const [copied,setCopied]=useState(false);return <button className="btn btn-secondary text-sm" onClick={async()=>{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy link'}</button>}
export function MobileMenu({items}:{items:{label:string;href:string}[]}){const [open,setOpen]=useState(false);return <div className="md:hidden"><button className="rounded-lg border bg-white p-2" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>{open&&<div className="absolute left-0 right-0 top-16 z-40 border-b bg-white p-4 shadow-lg">{items.map(i=><a key={i.href} onClick={()=>setOpen(false)} className="block rounded-lg px-3 py-3 font-medium hover:bg-slate-50" href={i.href}>{i.label}</a>)}</div>}</div>}
export function ProductSwitcher(){return <div className="relative"><details><summary className="cursor-pointer list-none rounded-lg px-2 py-1 text-xs font-semibold text-slate-500">BrellBook ▾</summary><div className="absolute right-0 top-8 z-30 w-48 rounded-xl border bg-white p-2 shadow-xl">{['BrellBook','BrellFlow','BrellPay','BrellChat','BrellAI','BrellAds','BrellStudio'].map((x,i)=><div key={x} className="rounded-lg px-3 py-2 text-sm font-medium hover:bg-slate-50">{x}{i>0&&<span className="ml-2 text-[10px] text-slate-400">Coming soon</span>}</div>)}</div></details></div>}
